// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxZBzsrPNVRjqv8qmKqidpKVihLtGnApY',
    appId: '1:870620403935:web:d1bd6587a6bce6108a716a',
    messagingSenderId: '870620403935',
    projectId: 'flutter-bookreview-2023',
    authDomain: 'flutter-bookreview-2023.firebaseapp.com',
    storageBucket: 'flutter-bookreview-2023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzycC36c57Mgnvx2RQBrB84XwlEIcd5Ss',
    appId: '1:870620403935:android:d265e4063254ffb28a716a',
    messagingSenderId: '870620403935',
    projectId: 'flutter-bookreview-2023',
    storageBucket: 'flutter-bookreview-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBpXAeQyKq-XuEd08qHjTNLxEkrJPLTBs',
    appId: '1:870620403935:ios:1ee8d17b70587bc38a716a',
    messagingSenderId: '870620403935',
    projectId: 'flutter-bookreview-2023',
    storageBucket: 'flutter-bookreview-2023.appspot.com',
    iosBundleId: 'com.itbebop.bookreview',
  );
}
